version: '3.9'

services:
  web:
    image: haorui215/jenkins-react
    ports:
      - '8888:80'
    configs:
      - source: nginx-confd
        target: /etc/nginx/conf.d/default.conf
        mode: 0444
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback

networks:
  frontend:

configs:
  nginx-confd:
    file: ./nginx/conf.d/default.conf
