def createVersion() {
    // result 20240131161412_22
    return new Date().format('yyyyMMddHHmmss') + "_${env.BUILD_ID}"
}

pipeline {
    agent any
    environment {
        _version = createVersion()
    }
    stages {
        stage ('Clone repository') {
            steps {
                checkout scm
            }
        }
        
        stage('Deploy') {
            steps {
                sshagent(['mbpkey']) {
                    sh 'ssh haorui@192.168.0.104 whoami'
                    sh 'ssh haorui@192.168.0.104 /usr/local/bin/docker ps'
                }
            }
        }
    }
}